---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/doctors":
    get:
      summary: Retrieves all doctors
      tags:
      - Doctors
      responses:
        '200':
          description: doctors found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    photo:
                      type: string
                    about:
                      type: string
                    price_hour:
                      type: integer
                  required:
                  - id
                  - name
                  - photo
                  - about
                  - price_hour
    post:
      summary: Creates a doctor
      tags:
      - Doctors
      parameters: []
      responses:
        '201':
          description: doctor created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                photo:
                  type: string
                about:
                  type: string
                price_hour:
                  type: integer
              required:
              - name
              - photo
              - about
              - price_hour
  "/api/doctors/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves a doctor
      tags:
      - Doctors
      responses:
        '200':
          description: doctor found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  photo:
                    type: string
                  about:
                    type: string
                  price_hour:
                    type: integer
                required:
                - id
                - name
                - photo
                - about
                - price_hour
        '404':
          description: doctor not found
    delete:
      summary: Deletes a doctor
      tags:
      - Doctors
      responses:
        '204':
          description: doctor deleted
        '404':
          description: doctor not found
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
